### ISSUE TITLE
bug in multiprocessing?

### ISSUE THREAD

**Issue by Gldkslfmsd** [Gldkslfmsd/concordance-crawler#28]
```
2016-04-13 09:30:33,466 STATUS: Crawling status 
serp    12 (0 errors) 
links crawled 600 (29 filtered because of format suffix, 1 crawled repeatedly)
pages visited 541 (1 filtered by encoding filter, 205 filtered by language filter, 10 errors)
concordances  3550 (156 crawled repeatedly)
2016-04-13 09:30:33,466 DEBUG: trying to download https://www.waukeshacounty.gov/Product_Disp/
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 420, in _handle_results
    task = get() 
  File "/usr/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __new__() missing 1 required positional argument: 'protocol'

2016-04-13 09:35:33,466 ERROR: request https://www.waukeshacounty.gov/Product_Disp/ cannot be handled for a long time
2016-04-13 09:35:33,466 DEBUG: trying to download https://en.wikipedia.org/wiki/Displacement
2016-04-13 09:40:33,467 ERROR: request https://en.wikipedia.org/wiki/Displacement cannot be handled for a long time
2016-04-13 09:40:33,467 DEBUG: trying to download http://www.disp.se/core.asp
2016-04-13 09:45:33,467 ERROR: request http://www.disp.se/core.asp cannot be handled for a long time
2016-04-13 09:45:33,468 DEBUG: trying to download https://beautiful-people.jp/products/list.php?category_id=13&view=look&disp_number=30
2016-04-13 09:50:33,468 ERROR: request https://beautiful-people.jp/products/list.php?category_id=13&view=look&disp_number=30 cannot be handled for a long time 
2016-04-13 09:50:33,469 DEBUG: trying to download http://www.chron.com/neighborhood/heights-news/article/Authorities-will-look-into-O-Quinn-s-speed-in-1730913.php
```

It worked 30 minutes without problems. Then the error occurred and after that every request was killed by the forked timer.

**Comment by Gldkslfmsd** [comment]
It seems to be solved, I removed the forking, but there are few other problems: terminating via Ctrl+C doesn't work and requests library logs some statuses, they should be debug messages, not statuses.

**Comment by Gldkslfmsd** [comment]
solved
